### ISSUE TITLE
Timeout issue with Hoist Data Pipeline

### ISSUE THREAD

**Issue by buildmaster** [hoist/Hoist#166]
[02:52:09] LOG {"bucket":{"key":"AMBvUEgo6PDNzVWRPb9jqrtN","meta":{"accountingPackage":"XERO","authToken":{"xero":"nf1GCmLsaaBU2u1huXUGeIMqUtXad2xJ"}},"updatedAt":"2015-05-01T06:24:09.926Z","environment":"live","deleted":false,"createdAt":"2015-05-01T06:23:52.047Z","application":"3p3V_5yIZR6QS_vdAZSo","__v":0,"_id":"LBOQmejBtylbyBMEpoj4"}}
[02:52:09] LOG "Load Connector"
[02:52:09] LOG "PRE LOAD"
[02:52:09] LOG "LOAD TRANSACTIONS"
[02:52:09] ERR server 172.16.2.173:27017 sockets closed
MongoError: server 172.16.2.173:27017 sockets closed
  at Server.destroy (/usr/src/app/node_modules/@hoist/connect/node_modules/@hoist/data-pipeline/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:655:47)
  at State.destroy (/usr/src/app/node_modules/@hoist/connect/node_modules/@hoist/data-pipeline/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset_state.js:157:33)
  at ReplSet.destroy (/usr/src/app/node_modules/@hoist/connect/node_modules/@hoist/data-pipeline/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset.js:693:20)
  at ReplSet.close (/usr/src/app/node_modules/@hoist/connect/node_modules/@hoist/data-pipeline/node_modules/mongodb/lib/replset.js:423:18)
  at Db.close (/usr/src/app/node_modules/@hoist/connect/node_modules/@hoist/data-pipeline/node_modules/mongodb/lib/db.js:321:19)
  at tryCatcher (/usr/src/app/node_modules/bluebird/js/main/util.js:26:23)
  at ret [as closeAsync](eval at  %28/usr/src/app/node_modules/bluebird/js/main/promisify.js:163:12%29, :12:23)
  at null._onTimeout (/usr/src/app/node_modules/@hoist/connect/node_modules/@hoist/data-pipeline/lib/mongo_connection.js:66:29)
  at Timer.listOnTimeout (timers.js:89:15)

**Comment by buildmaster** [comment]
reported by @bobbynewmark and affecting Tracks too

**Comment by buildmaster** [comment]
fixed with https://github.com/hoist/hoist-data-pipeline/commit/5c184bfac86478087ad1bc01ea23e42db0212509
